### ISSUE TITLE
[8086] Toshiba T1200 keeps rebooting after memory test

### ISSUE THREAD

**Issue by usergithub64** [PCBox/PCBox#59] opened 2023-04-24 15:52 UTC
**Describe the bug**
[8086] Toshiba T1200 keeps rebooting after memory test. This happens both through PCBox and through 86Box Manager v1.7.4 in dev builds. In regular PCBox builds everything works fine. In 86Box builds everything works fine.

**To Reproduce**
1. Create machine [8086] Toshiba T1200.
2. Start the machine in PCBox or via 86Box Manager v1.7.4.
2. See error.

**Expected behavior**
[8086] Toshiba T1200 in PCBox should not reboot after memory test.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v22H2
 - PCBox v4.0 x64 (PCBox-NDR-Dev-Windows-MINGW64-gha726)
 - Build type: dev, old or new recompiler.

**Comment by fuel-pcbox** [comment] 2023-04-28 05:39
Weird, because I haven't changed ANYTHING about that machine lol

**Comment by fuel-pcbox** [comment] 2024-08-05 05:16
Can't reproduce this. Closing.

**Closed as completed by fuel-pcbox** 2024-08-05 05:16 UTC
Labels: bug
