### ISSUE TITLE
[SCAT] GW-286CT GEAR freeze

### ISSUE THREAD

**Issue by usergithub64** [PCBox/PCBox#58] opened 2023-04-22 13:50 UTC
**Describe the bug**
[SCAT] GW-286CT GEAR hangs when starting the machine (only POST card codes flicker). The machine freezes at startup, both through PCBox and through 86Box Manager v1.7.4. This bug was introduced in build PCBox-NDR-Dev-Windows-MINGW64-gha726 and persists until the last build. In build PCBox-NDR-Dev-Windows-MINGW64-gha725 everything works fine.

**To Reproduce**
1. Create an [SCAT] GW-286CT GEAR machine.
2. Start the machine in PCBox or via 86Box Manager v1.7.4.
3. See error.

**Expected behavior**
The machine [SCAT] GW-286CT GEAR in PCBox should not freeze.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v22H2
 - PCBox v4.0 x64 (PCBox-NDR-Dev-Windows-MINGW64-gha726)
 - Build type: dev, old or new recompiler.

**Comment by fuel-pcbox** [comment] 2023-04-28 05:38
This should also happen in 86Box as well then, try testing it there.

**Comment by usergithub64** [comment] 2023-04-28 07:55
In build 86Box-Windows-64-b4573 everything works fine.

**Comment by fuel-pcbox** [comment] 2023-04-30 16:47
Strange, try a Qt CMake build of PCBox maybe?

**Comment by fuel-pcbox** [comment] 2024-08-05 05:18
Can't reproduce this either. Closing.

**Closed as completed by fuel-pcbox** 2024-08-05 05:18 UTC
Labels: bug
